apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{.Values.falco.falcosidekick.webui.redis.storageClass | quote}}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    app.kubernetes.io/part-of: platform-baseline
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: gp3
